name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Código Limpio (Flake8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install flake8

      - name: Revisar calidad del código con Flake8
        run: flake8 --max-line-length=180

  test:
    name: Pruebas Unitarias (pytest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest boto3 beautifulsoup4

      - name: Ejecutar pruebas con pytest
        run: pytest Tests/

  deploy:
    name: Despliegue en AWS con Zappa
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar Zappa
        run: pip install zappa

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-1

      - name: Desplegar con Zappa
        run: zappa update dev
