name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Código Limpio (Flake8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install flake8

      #- name: Revisar calidad del código con Flake8
       # run: flake8 --max-line-length=180

  test:
    name: Pruebas Unitarias (pytest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar dependencias y configurar entorno virtual
        run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip wheel
          venv/bin/pip install "setuptools<58.0.0"
          venv/bin/pip install -r requirements.txt
          venv/bin/pip install pytest boto3 beautifulsoup4 "moto<5.0" awscli zappa

      - name: Configurar PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Verificar estructura de archivos
        run: ls -R

      - name: Ejecutar pruebas con pytest
        run: venv/bin/pytest Tests/

  deploy:
    name: Despliegue en AWS con Zappa
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar dependencias y configurar entorno virtual
        run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip wheel
          venv/bin/pip install "setuptools<58.0.0"
          venv/bin/pip install -r requirements.txt
          venv/bin/pip install boto3 beautifulsoup4 awscli zappa

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Verificar conexión con AWS S3
        run: venv/bin/aws s3 ls

      - name: Deploy with Zappa
        run: |
          source env/bin/activate  # Activar entorno virtual
          cd Parsing
          ls  # Verificar archivos dentro de Parsing
          
          if zappa status dev_parser || true; then
            zappa update dev_parser
          else
            zappa deploy dev_parser
          fi
        

      # 🔹 Paso 7: Verificar despliegue
      - name: Check Zappa Status
        run: |
          source env/bin/activate  # Activarlo
          cd Parsing
          zappa status dev_parser
